// SPDX-License-Identifier: GPL-2.0
/*
 * arm64 subarch half of UML's /proc/cpuinfo.
 *
 * There is no CPUID bitmap to mirror here. What a UML/arm64 guest can honestly
 * claim is what the host actually granted the UML process:
 *
 *   - AT_HWCAP / AT_HWCAP2 from the auxiliary vector, which is what guest
 *     userspace (glibc's ifunc resolvers, OpenSSL, ...) really consults;
 *   - the host's own "Features" line, echoed back so that anything reading
 *     /proc/cpuinfo sees names in arm64's format rather than x86's.
 *
 * Deriving the names from the host string rather than from a table indexed by
 * KERNEL_HWCAP_* is deliberate: that table is generated by arch/arm64/tools
 * during an arm64 kernel build, which does not run for ARCH=um, and hardcoding
 * a copy of it would go stale against whatever host the binary is run on.
 */
#include <linux/init.h>
#include <linux/kernel.h>
#include <linux/seq_file.h>
#include <linux/string.h>

#include <asm/processor.h>
#include <arch.h>

extern long elf_aux_hwcap;
extern long elf_aux_hwcap2;

/*
 * The host's "Features" list, captured verbatim (minus the field name and the
 * trailing newline). arm64 hosts list on the order of 40 short names; 512 bytes
 * is comfortably above that and the string is truncated rather than overflowed
 * if a future host exceeds it.
 */
static char host_features[512];
static bool host_features_valid;

void arch_show_cpuinfo(struct seq_file *m)
{
	/*
	 * "Features" is the arm64 spelling; guest userspace and lscpu both look
	 * for that key, not for x86's "flags".
	 */
	seq_printf(m, "Features\t: %s\n",
		   host_features_valid ? host_features : "");
	seq_printf(m, "hwcap\t\t: 0x%lx\n", (unsigned long)boot_cpu_data.arch.hwcap);
	seq_printf(m, "hwcap2\t\t: 0x%lx\n", (unsigned long)boot_cpu_data.arch.hwcap2);
}

int arch_parse_host_cpu_flags(char *line)
{
	char *value;
	size_t len;

	/*
	 * Record the auxv values on the first call; they come from the host
	 * kernel directly and are the authoritative answer, independent of how
	 * /proc/cpuinfo happens to be formatted.
	 */
	boot_cpu_data.arch.hwcap = elf_aux_hwcap;
	boot_cpu_data.arch.hwcap2 = elf_aux_hwcap2;

	if (strncmp(line, "Features", 8))
		return 0;

	value = strchr(line, ':');
	if (!value)
		return 0;
	value++;
	while (*value == ' ' || *value == '\t')
		value++;

	strscpy(host_features, value, sizeof(host_features));
	len = strlen(host_features);
	while (len && (host_features[len - 1] == '\n' ||
		       host_features[len - 1] == ' '))
		host_features[--len] = '\0';
	host_features_valid = true;

	/*
	 * arm64's /proc/cpuinfo has no cache_alignment field and repeats the
	 * same Features line for every core, so once it is seen there is
	 * nothing further to read.
	 */
	return 1;
}
